#!/usr/bin/env python3
"""Provided machinery for Week 2 line following.

Students do not edit this file. It wires the four functions in
``line_follower.py`` into the car control server: it runs the pipeline,
applies the PID controller, and hands the result to the debug overlay.

The student-facing ``LineFollower`` subclasses ``LineFollowerBase`` and
implements ``process()`` plus the four image functions. The tunable
parameters (ROI fractions, Canny thresholds, PID gains) are defined in the
subclass so they all live in one place alongside the code that uses them.
"""

import time

import numpy as np

from week2_line_following.debug_overlay import render_overlay


class LineFollowerBase:
    def __init__(self):
        # PID accumulator state.
        self.previous_error = 0.0
        self.integral_error = 0.0
        self.last_time = time.time()

        # Latest pipeline values, set by process() and read by the debug
        # overlay. They start as harmless defaults so the UI runs before the
        # student functions are implemented.
        self.roi_bounds = (0, 0, 0, 0)
        self.image_center_x = None
        self.line_center_x = None
        self.line_center_y = None
        self.edge_image = None
        self.current_error = 0.0

        # Telemetry consumed by the web UI sidebar.
        self.debug_frame = None
        self.current_debug_data = {
            "error_px": 0.0,
            "steering_angle": 0.0,
            "lines_detected": 0,
        }

    def compute_steering_angle(self, frame, debug_level=0):
        """Entry point called by the car control server for each frame."""
        if frame is None:
            return 0.0
        try:
            steering_angle = self.process(frame)
            self._update_debug(frame, steering_angle, debug_level)
            return float(steering_angle)
        except Exception as exc:
            print(f"Processing error: {exc}")
            return 0.0

    def apply_pid(self, error):
        """Convert a pixel error into a clipped steering angle."""
        now = time.time()
        dt = now - self.last_time
        if dt <= 0:
            dt = 0.1

        proportional = self.Kp * error
        self.integral_error += error * dt
        integral = self.Ki * self.integral_error
        derivative = self.Kd * (error - self.previous_error) / dt

        steering_angle = np.clip(proportional + integral + derivative, -30, 30)

        self.previous_error = error
        self.last_time = now
        return float(steering_angle)

    def _update_debug(self, frame, steering_angle, debug_level):
        self.current_debug_data.update({
            "error_px": round(float(self.current_error), 1),
            "steering_angle": round(float(steering_angle), 1),
            "lines_detected": 1 if self.line_center_x is not None else 0,
        })
        if debug_level > 0:
            self.debug_frame = render_overlay(frame, debug_level, self)
        else:
            self.debug_frame = frame.copy()

    def get_debug_frame(self):
        return self.debug_frame

    def reset_integral(self):
        self.integral_error = 0.0

    def update_parameters(self, **kwargs):
        """Update tunable parameters live from the web UI."""
        parameter_map = {
            "kp": "Kp", "ki": "Ki", "kd": "Kd",
            "canny_low": "canny_low", "canny_high": "canny_high",
            "roi_top": "roi_top", "roi_bottom": "roi_bottom",
            "roi_left": "roi_left", "roi_right": "roi_right",
        }
        for input_name, attribute_name in parameter_map.items():
            value = kwargs.get(input_name)
            if value is not None:
                setattr(self, attribute_name, value)

    def process(self, frame):
        """Implemented by the student-facing subclass."""
        raise NotImplementedError
